name: Releasator

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  sendPostRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Extract repo name
        id: get_repo
        run: echo "::set-output name=repo::${GITHUB_REPOSITORY}"

      - name: Send POST request
        uses: fjogeleit/http-request-action@master
        with:
          silent: true
          url: 'https://releasator.ru-web-designer.workers.dev/api/releases'
          method: 'POST'
          contentType: 'application/json'
          headers: |
            Authorization: Bearer ${{ secrets.RELEASATOR_TOKEN }}
          data: >
            {
              "repo": "${{ steps.get_repo.outputs.repo }}",
              "head": {
                "type": "tag",
                "name": "${{ steps.get_tag.outputs.tag }}"
              }
            }
